version: "3"

services:
  app:
    build: .
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - laravelnet

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravelnet

networks:
  laravelnet: